version: '3'
services:
  postgres:
    image: postgres
    container_name: mewa-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: mewa-workshop
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
  # redis:
  #   image: redis
  #   container_name: mewa-redis
  #   ports:
  #     - 6379:6379
  #   restart: always
