import { Inter } from 'next/font/google';
import { Menu } from '../components';
import { Footer } from '../components/Footer';
import './styles.css';

export const metadata = {
  title: 'Welcome to website',
  description: 'Generated by create-nx-workspace',
};

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <div className="flex flex-col h-screen">
          <Menu />
          <main className="container mx-auto">
            {children}
          </main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
