import { Inter, Roboto, Galindo } from 'next/font/google'; // 643 (gzipped: 377)
import './styles.css';

export const metadata = {
  title: 'Welcome to website',
  description: 'Generated by create-nx-workspace',
};

// const inter = Inter({ subsets: ['latin'] });
// const roboto = Roboto({ weight: ['400', '700'], subsets: ['latin'] });
const galindo = Galindo({ weight: ['400'], subsets: ['latin'] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${galindo.className}`}>
        {children}
      </body>
    </html>
  );
}
